[0m15:14:16.895168 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106c9b950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113d6d790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113d6d4c0>]}


============================== 15:14:16.898139 | ac382561-6b2f-437f-ad47-be7d84a6252c ==============================
[0m15:14:16.898139 [info ] [MainThread]: Running with dbt=1.10.7
[0m15:14:16.898408 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/yashvi/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init nyc_taxi_dbt', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:14:16.903157 [debug] [MainThread]: Starter project path: /opt/anaconda3/envs/TaxiDataVEnv/lib/python3.12/site-packages/dbt/include/starter_project
[0m15:14:16.906267 [info ] [MainThread]: 
Your new dbt project "nyc_taxi_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m15:14:16.906428 [info ] [MainThread]: Setting up your profile.
[0m15:15:49.606370 [info ] [MainThread]: Profile nyc_taxi_dbt written to /Users/yashvi/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m15:15:49.609914 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 92.749794, "process_in_blocks": "0", "process_kernel_time": 0.126263, "process_mem_max_rss": "113229824", "process_out_blocks": "0", "process_user_time": 0.719824}
[0m15:15:49.610630 [debug] [MainThread]: Command `dbt init` succeeded at 15:15:49.610495 after 92.75 seconds
[0m15:15:49.611305 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113f8afc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113d94770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113f446e0>]}
[0m15:15:49.611817 [debug] [MainThread]: Flushing usage events
[0m15:15:49.961655 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:16:34.343374 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074d2540>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094197c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109419550>]}


============================== 15:16:34.345562 | a80a2d3d-5991-4da8-83c9-1337770858bc ==============================
[0m15:16:34.345562 [info ] [MainThread]: Running with dbt=1.10.7
[0m15:16:34.345818 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/yashvi/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:16:34.350059 [info ] [MainThread]: dbt version: 1.10.7
[0m15:16:34.350195 [info ] [MainThread]: python version: 3.12.2
[0m15:16:34.350468 [info ] [MainThread]: python path: /opt/anaconda3/envs/TaxiDataVEnv/bin/python3.12
[0m15:16:34.350617 [info ] [MainThread]: os info: macOS-15.6-arm64-arm-64bit
[0m15:16:34.374260 [info ] [MainThread]: Using profiles dir at /Users/yashvi/.dbt
[0m15:16:34.374525 [info ] [MainThread]: Using profiles.yml file at /Users/yashvi/.dbt/profiles.yml
[0m15:16:34.374674 [info ] [MainThread]: Using dbt_project.yml file at /Users/yashvi/Documents/Study/Data Analysis Projects/Projects/Taxi DE w: Mage/dbt_project.yml
[0m15:16:34.374917 [info ] [MainThread]: adapter type: postgres
[0m15:16:34.375046 [info ] [MainThread]: adapter version: 1.9.0
[0m15:16:34.375175 [info ] [MainThread]: Configuration:
[0m15:16:34.375292 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m15:16:34.375406 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m15:16:34.375510 [info ] [MainThread]: Required dependencies:
[0m15:16:34.375657 [debug] [MainThread]: Executing "git --help"
[0m15:16:34.384160 [debug] [MainThread]: STDOUT: "b''"
[0m15:16:34.384538 [debug] [MainThread]: STDERR: "b'xcode-select: note: No developer tools were found, requesting install.\nIf developer tools are located at a non-default location on disk, use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, and cancel the installation dialog.\nSee `man xcode-select` for more details.\n'"
[0m15:16:34.384715 [debug] [MainThread]: command return code=1
[0m15:16:34.385068 [error] [MainThread]: Encountered an error:
Got a non-zero returncode running: ['/usr/bin/git', '--help']
[0m15:16:34.386272 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.07267229, "process_in_blocks": "0", "process_kernel_time": 0.08486, "process_mem_max_rss": "113901568", "process_out_blocks": "0", "process_user_time": 0.562457}
[0m15:16:34.386512 [debug] [MainThread]: Command `dbt debug` failed at 15:16:34.386474 after 0.07 seconds
[0m15:16:34.386696 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107badc10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10952de20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109419310>]}
[0m15:16:34.386859 [debug] [MainThread]: Flushing usage events
[0m15:16:34.680825 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:18:49.392609 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1090da1b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1096f9f10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109745910>]}


============================== 22:18:49.395536 | c3d9da12-9c2d-4b03-9bc2-02400598cdf7 ==============================
[0m22:18:49.395536 [info ] [MainThread]: Running with dbt=1.10.7
[0m22:18:49.395805 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/yashvi/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run --select stg_nyc_taxi_data', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:18:49.396058 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/yashvi/Documents/Study/Data Analysis Projects/Projects/Taxi DE w: Mage/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:18:49.397192 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.038503543, "process_in_blocks": "0", "process_kernel_time": 0.098913, "process_mem_max_rss": "109199360", "process_out_blocks": "0", "process_user_time": 0.543085}
[0m22:18:49.397402 [debug] [MainThread]: Command `dbt run` failed at 22:18:49.397364 after 0.04 seconds
[0m22:18:49.397536 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108e65070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109745a30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1097471a0>]}
[0m22:18:49.397662 [debug] [MainThread]: Flushing usage events
[0m22:18:49.744617 [debug] [MainThread]: An error was encountered while trying to flush usage events
